### ISSUE TITLE
[Discussion] State of the project

### ISSUE THREAD

**Issue by saschagrunert** [containerbuilding/cbi#81]
Hey 👋 I was wondering why native image building support is no thing in Kubernetes and came across this project. It looks very promising but seems to lack a bit popularity. 

So what is the State of the project? Are you considering in actively pushing it forward in the future? :)

**Comment by AkihiroSuda** [comment]
> Are you considering in actively pushing it forward in the future? :)

No I lost to Knative Build :sweat_smile: 

I'll update README to clarify the current status.

**Comment by saschagrunert** [comment]
That's nice, thanks! What does _lost_ mean in your view? I mean knative seems to follow different approaches like this project. :)
